language:
- scala

scala:
- 2.11.7

jdk:
- oraclejdk8

notifications:
  email: false

branches:
  only:
  - master
  - develop

script:
- sbt clean test

after_success:
- sbt clean coverage test coverageReport coveralls
