language:
  - scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

notifications:
  email: false

branches:
  only:
    - master
    - develop

script:
  - sbt clean compile
  - sbt test:compile
  - sbt functional:compile
  - sbt performance:compile

after_success:
  - sbt coverage test functional:test
  - sbt coverageReport coveralls
