language:
  - scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

notifications:
  email: false

branches:
  only:
    - master
    - develop

script:
  - sbt clean compile
  - sbt compile:test
  - sbt compile:functional
  - sbt compile:performance

after_success:
  - sbt coverage test functional:test
  - sbt coverageReport coveralls
