sudo: required

dist: trusty

language: scala

scala:
  - 2.12.0

jdk:
  - oraclejdk8
  - openjdk8

notifications:
  email: false

branches:
  only:
    - master
    - develop

script:
  - sbt clean compile test:compile functional:compile performance:compile

after_success:
  - sbt coverage test
  - sbt functional:test
  - sbt coverageReport coveralls

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/